version: "3.7"
services:
  notebook:
    image: jupyter/all-spark-notebook:latest
    env_file:
      - .env
    ports:
      - 8888:8888
      - 4040:4040
  localstack-s3:
    image: localstack/localstack:0.10.7
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - 4567-4584:4567-4584
      - 8055:8080
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
      - ./data/s3:/tmp/localstack
  spark-master:
    image: spark:2.4.5-worker
    container_name: spark-master
    hostname: spark-master
    env_file:
      - .env
    command: "/usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master --port $SPARK_MASTER_PORT --webui-port $SPARK_MASTER_WEBUI_PORT"
    ports:
      - "8080:8080"
    volumes:
      - ./log4j.properties:/usr/local/spark/conf/log4j.properties
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker-1:
    image: spark:2.4.5-worker
    container_name: spark-worker-1
    hostname: spark-worker-1
    env_file:
      - .env
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./log4j.properties:/usr/local/spark/conf/log4j.properties
